const LOGIN = {
  REQUEST: 'LOGIN_REQUEST',
  SUCCESS: 'LOGIN_SUCCESS',
  ERROR: 'LOGIN_ERROR',
  UNAUTHORIZED: 'LOGIN_UNAUTHORIZED',
  LOGOUT: 'LOGOUT',
  DELETE_TOKEN: 'DELETE_TOKEN',
  SAVE_TOKEN: 'SAVE_TOKEN',
  CANCELLED: 'LOGIN_CANCELLED',
  ADD_EMAIL: 'ADD_EMAIL',
  STORE_USER: 'STORE_USER'
}

const SHOPPING = {
  ADD_PRODUCT: 'ADD_PRODUCT',
  REMOVE_PRODUCT: 'REMOVE_PRODUCT',
  UPDATE_AMOUNT: 'UPDATE_AMOUNT',
  RESET_CART: 'RESET_CART',
}

export { LOGIN, SHOPPING }